### ISSUE TITLE
-c param

### ISSUE THREAD

**Issue by mjmontague** [LynchLab/MAPGD#22]
I'd like to run MAPGD on ~200 individuals, and I've created mpileup and pro files for each from the bam alignments. Some samples are low coverage (1-2x) and others range from 6x-40x. Could you provide details on the -c and -C params?

The manual states that for analyzing individual labeled data I will use a command like this:

samtools mpileup -q 25 -Q 25 -B population1.sort.bam population2.sort.bam 
| mapgd proview -H seq1.header | mapgd allele | mapgd filter -p 22 -E 0.01 -c 50 -C 200 -o allelefrequency-filtered.map.

where the population coverage is between 50 and 200.

Do I actually need a single multi-sample mpileup file?

Both examples (pooled and individual) have “samtools mpileup -q 25 -Q 25 -B population1.sort.bam population2.sort.bam“ as the first line, which is confusing.

**Comment by LynchLab** [comment]
First off, sorry it took me so long to get to this. 

OK, the -c and -C parameters filter on the population level coverage, so if the total number of reads from all individuals mapping to the site are outside of these boundaries the site is removed from analysis.

You do not need a single multi-sample mpileup file. To use multiple mpileup files as input type mapgd proview -i *.mpileup -H seq1.header, or, alternatively, if you want to manually name the samples in the mpileup files, mapgd -n name-file.txt -H  seq1.header ....

The format of the name-file isn't document right now, because it isn't really a permanent feature, but it  is simply the name of the file to open (with the right path relative to wherever you are calling mapgd) and followed by the name of each sample in the file, tab delimited. If you want to use multiple files as input, just specify multiple lines.

I'll try to fix up the README.md file. 

Hope that helps. 

-Matt
