### ISSUE TITLE
fifo and pipeline suggested in quick start guide

### ISSUE THREAD

**Issue by dseok** [LynchLab/MAPGD#23]
In the Mapgd quick start guide, this command is suggested to generate a linkage file:

`mkfifo map;
mkfifo pro;
samtools mpileup -q 25 -Q 25 -B population1.sort.bam population2.sort.bam 
| mapgd proview -H seq1.header | mapgd allele -p pro | mapgd filter -p 22 -E 0.01 -c 50 -C 200 > map;
mapgd linkage -p pro -m map > population-lnk.out`

The allele command and the -p flag cause a file called "pro.pro" to be generated. Is this intended? Or should the command be something like 
`mkfifo map;
mkfifo pro;
samtools mpileup -q 25 -Q 25 -B population1.sort.bam population2.sort.bam 
| mapgd proview -H seq1.header > pro; mapgd allele -i pro | mapgd filter -p 22 -E 0.01 -c 50 -C 200 > map;
mapgd linkage -p pro -m map > population-lnk.out`   ?

I'm also aware that using I/O redirection with the proview command doesn't generate an .idx file. How does this affect the named pipe?

Thanks so much
Darsol

**Comment by LynchLab** [comment]
Hmm. There are a couple of things at work here. The "correct" way to use named pipes right now is with the 'tee' command, so "mapgd proview -H seq1.header | tee pro | mapgd allele -c 4 | mapgd filter -p 22 -E 0.01 -c 50 -C 200 > map &; mapgd linkage -p pro -m map > population-lnk.out"
I've tried to correct this in the readme. 
The second issue is that I would technically slightly prefer using the pro.pro file generated by the "mapgd allele -c 4 -p pro" command to the one being generated by the "tee pro" command because the "mapgd allele -c 4 -p pro" file has some sites removed for quality concerns which cannot be removed from  "tee pro" file by any other step. Currently there is noway to redirect the output of "mapgd allele -c 4 -p pro" to a named pipe. I'll add this to may todo list.
 
The lack of idx file isn't an issue because that information is just present in the beginning of the file generated by i/o redirection. This should all be made more clear in my readme.

**Comment by dseok** [comment]
thank you!
