### ISSUE TITLE
Failing test for deprecated SQL Functions

### ISSUE THREAD

**Issue by cfljam** [LynchLab/MAPGD#32]
make test fails at the mapgd write/read commands

```
../../bin/mapgd sam2idx -H spitze-header.txt | ../../bin/mapgd write -d test.db
mapgd: invalid command -- 'write'
usage: mapgd COMMAND [OPTIONS]
Try 'mapgd --help' for more information.
../../bin/mapgd read -d test.db -t REGIONS                                                                              mapgd: invalid command -- 'read'
usage: mapgd COMMAND [OPTIONS]
Try 'mapgd --help' for more information.
0 write.out
expected 6
[write] write/read FAIL
Makefile:51: recipe for target 'test' failed
make[1]: Leaving directory '/MAPGD-master/src'
make[1]: *** [test] Error 1
make: *** [test] Error 2
Makefile:94: recipe for target 'test' failed
The command '/bin/sh -c wget -O MAPGD.zip $GIT_URL  &&   unzip MAPGD.zip &&   cd MAPGD* &&   ./configure &&   make && make install && make test' returned a non-zero code: 2


```

**Comment by matthew-ackerman** [comment]
It might be a problem with different versions of SQLite3. The version on
GitHub passes, and it works for me on a desktop with sqlite3 3.8.2, but it
fails for me with sqlite3 3.7.9. What version of sqlite3 are you using?
'sqlite3 -version'.

-Matt

**Comment by matthew-ackerman** [comment]
Okay, it looks like the support for insert statements accepting
comma-separated lists of values was added in version 3.7.11
<http://www.sqlite.org/releaselog/3_7_11.html>, so I'm adding an insert
statement that iterates through a list, instead of trying to do everything
with one statement. It may take some time to get the option set by the
configuration file, but I'll come up with a flag to support compilation in
the meantime. Just a few more minutes I think.

-Matt

**Comment by matthew-ackerman** [comment]
It seems to be working with older versions of SQLite3 now. Let me know if this fails to fix your problems.

**Comment by matthew-ackerman** [comment]
It seems to be passing test now on older versions of sqlite3. Let me know if this didn't work for you.
