### ISSUE TITLE
continuous pooled data from unknown number of individuals

### ISSUE THREAD

**Issue by stsmall** [LynchLab/MAPGD#7]
Dear Dr. Lynch,
thank you for working on this code.
I have 2 populations I would like to run a sliding window Fst analysis.
The 1st population is composed of 13 individual diploid genomes with SNPs called and filtered via freebayes. The 2nd population, and here is the crux of the issue, is a pooled population of an unknown number of genomes. Unknown because it is from a parasite infection with multiple parasites per blood sample. I have also used freebayes with the continuous-pool option to call and filter SNPs. 
Finally the questions:
1) Can I use MAPGD on the continuous-pooled population or must I know the number of pooled individuals?
2) Would it be better to run the cont-pooled.bam through mpileup, such that the .pro will contain rare alleles or just convert directly from vcf as I intend to do with the 13 individual diploid genomes?

Also as a note... this individual https://github.com/owensgl/reformat/blob/master/vcf2pro.pl wrote a script for converting vcf2pro which may be useful to users until you have a chance to supply your own.

Thank you,
scott

**Comment by LynchLab** [comment]
First of all, MAPGD is intended for use on raw data. It cannot work with
only a set of filtered snps, because it needs sequence of sites that are
presumed to be homozygous in order to estimate rates at which errors occur
during sequencing and the rate at which heterozygousity is missed.

1) You can use MAPGD on pooled population sequence. The command to do this
is mapgd cp, which calculate the maximum likelihood allele frequency in two
pooled populations, and the chi-squared distributed log likelihood ratio
between the null model (that both populations have the same allele
frequency) and the best fit model (that the two populations have different
allele frequencies).

I don't believe vcf files contain the information necessary to construct
profiles. The command to construct profiles is 'mapgd proview' and it takes
the output of the command 'samtools mpileup'. I think I've got an example
pipeline somewhere in the readme, but the command should be 'samtools
mpileup *.bam | mapgd proview | mapgd cp'

Also, it sounds like you want to compare one population where the
individuals are indexed, to a another population where the individuals are
not. Currently we do not  have a command for this, although the form of the
likelihood function is only trivially different from the functions we are
currently using, so it should be a cinch to write.

Unfortunately, I'm in the middle of an extensive re-write of the code, and
adding the command might get dropped to the bottom of an extensive to do
list. I can add new command soon (maybe within a week?), but would you be
willing to write me a few dozen reminder emails until it gets done? I tend
to drop projects that people don't express sufficient interest in.

-Matt

**Comment by stsmall** [comment]
Hi Matt,
Thank you for the reply. It is great that I can use MAPGD on my pooled sample since I haven't found many other programs.

You are correct that a .pro file should include the reads from all positions in the quartet even if this position is found to be homozygotic. Do you think that a gVCF file from callers like GATK, (https://www.broadinstitute.org/gatk/guide/article?id=4017) would be possible to transform into a .pro? The gVCF has information on all positions in the genome, not just the heterozygotes, and should be simple to transform into the quartet since read info for each allele is retained.

I greatly appreciate you adding a command for the pooled vs indexed comparison. I will send a few reminder emails through out the week.
thanks,
scott

**Comment by LynchLab** [comment]
I don't believe it is possible to reconstruct a vcf file into a pro file
because I don't believe that calls related to alleles that are adjudicated
to be 'errors' are retained in the file. But I could be wrong. As long as a
pro file really can be reconstructed, then it should be fine.
